Traceback (most recent call last):
  File "f:/python-class/exams/exception.py", line 3, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
